import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased min-h-dvh flex flex-col dark bg-gradient-to-b from-[#2d2d2d] to-black '>
        {children}
      </body>
    </html>
  );
}
