import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from '@/contexts/user-context';
import { ThemeProvider } from '@/contexts/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='antialiased min-h-dvh flex flex-col'>
        <UserProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            {children}
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
